import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb

from utils.get_dfs import get_metabs, get_metab_annotations, get_metab_platforms, get_mass_and_RI, get_unknowns_mass_RI


def get_sp_pred_data():

	Y = get_metab_annotations()
	Y = Y[['Sub pathway']]
	keep = Y['Sub pathway'].value_counts().sort_values(ascending=False)
	keep = set(keep[keep > 10].index)
	Y = Y[Y['Sub pathway'].isin(keep)]

	X = get_metabs(min_impute=True, rzscore=True).T
	m_raw = get_metabs(min_impute=False, rzscore=False).T
	X['sparsity'] = m_raw.isnull().sum(axis=1)
	X['raw_mean'] = m_raw.mean(axis=1)
	m_platforms = get_metab_platforms()
	m_platforms['Extraction Platform'] = m_platforms['Extraction Platform'].map({'LC/MS Pos Early':0,
															'LC/MS Pos Late':1,
															'LC/MS Polar':2,
															'LC/MS Neg':3})
	X = X.join(m_platforms)
	mass_and_ri = get_mass_and_RI()
	X = X.join(mass_and_ri)
	X = X.loc[Y.index]

	return X, Y



def figures_S8ABD():

	## Define our Y
	X, Y = get_sp_pred_data()

	## Explicitly set sample order to reproduce exact predictions generated by the 
	## best model in the random grid search
	order = ['(N(1) + N(8))-acetylspermidine', '1,2,3-benzenetriol sulfate (1)', '1,2,3-benzenetriol sulfate (2)', '1-carboxyethylhistidine',
	'1-carboxyethylisoleucine', '1-carboxyethylleucine', '1-carboxyethyltyrosine', '1-carboxyethylvaline',
	'1-methyl-4-imidazoleacetate', '1-methyl-5-imidazoleacetate', '1-methyl-5-imidazolelactate', '1-methyladenine',
	'1-methylhistamine', '1-methylhistidine', '1-ribosyl-imidazoleacetate*', "2'-deoxyadenosine", 
	'2,3-dihydroxy-2-methylbutyrate', '2,3-dihydroxy-5-methylthio-4-pentenoate (DMTPA)*',
	'2,3-dihydroxyisovalerate', '2-acetamidophenol sulfate', '2-aminoadipate', '2-aminophenol sulfate',
	'2-hydroxy-3-methylvalerate', '2-hydroxy-4-(methylthio)butanoic acid', '2-hydroxyadipate', '2-hydroxyglutarate',
	'2-hydroxyhippurate (salicylurate)', '2-hydroxysebacate', '2-isopropylmalate', '2-methoxyhydroquinone sulfate (1)',
	'2-methoxyhydroquinone sulfate (2)', '2-methylbutyrylcarnitine (C5)', '2-oxoarginine*', '2-piperidinone', '3-(4-hydroxyphenyl)lactate (HPLA)',
	'3-amino-2-piperidone', '3-formylindole', '3-hydroxy-2-ethylpropionate', '3-hydroxy-2-methylpyridine', '3-hydroxy-2-methylpyridine sulfate', '3-hydroxyadipate',
	'3-hydroxydodecanedioate*', '3-hydroxyhippurate', '3-hydroxyisobutyrate', '3-hydroxypyridine sulfate', '3-hydroxystachydrine*',
	'3-indoxyl sulfate', '3-methoxycatechol sulfate (1)', '3-methyl catechol sulfate (1)', '3-methyl-2-oxobutyrate',
	'3-methyladipate', '3-methylglutaconate', '3-methylglutarate/2-methylglutarate', '3-methylglutarylcarnitine (2)',
	'3-methylhistidine', '3-sulfo-L-alanine', '4-acetamidobutanoate', '4-acetylphenyl sulfate', '4-allylcatechol sulfate',
	'4-ethylcatechol sulfate', '4-ethylphenyl sulfate', '4-hydroxyglutamate', '4-hydroxyhippurate', '4-imidazoleacetate',
	'4-methylcatechol sulfate', '4-methylguaiacol sulfate', '4-vinylcatechol sulfate', '4-vinylphenol sulfate',
	'5-(galactosylhydroxy)-L-lysine', '5-aminovalerate', '5-hydroxy-2-methylpyridine sulfate', '5-hydroxylysine',
	'5-methylthioadenosine (MTA)', '6-hydroxyindole sulfate', '6-oxopiperidine-2-carboxylate', 'acesulfame', 'adenine',
	'adenosine', "2'-AMP", "adenosine 3',5'-cyclic monophosphate (cAMP)", "3'-AMP", 'AMP', 'adipate', 'agmatine', 'alanylleucine',
	'allo-threonine', 'alpha-hydroxyisocaproate', 'alpha-hydroxyisovalerate', 'alpha-ketoglutaramate*', 'anserine', 'argininate*',
	'arginine', 'argininosuccinate', 'azelate (C9-DC)', 'behenoyl sphingomyelin (d18:1/22:0)*', 'beta-citrylglutamate',
	'beta-guanidinopropanoate', 'beta-hydroxyisovalerate', 'beta-hydroxyisovaleroylcarnitine', 'betaine', 'betaine aldehyde',
	'C-glycosyltryptophan', 'cadaverine', 'carboxyethyl-GABA', 'catechol sulfate', 'cinnamoylglycine', 'cis-urocanate',
	'citrulline', 'cyclic adenosine diphosphate-ribose', 'cystathionine', 'cysteine', 'cystine', 'dexpanthenol',
	'diacetylspermidine*', 'diethanolamine', 'diglycerol', 'dihydrocaffeate sulfate (2)', 'dimethylarginine (ADMA + SDMA)',
	'dimethylglycine', 'dimethylmalonic acid', 'dopamine 3-O-sulfate', 'dopamine 4-sulfate', 'EDTA', 'erythritol',
	'ethyl alpha-glucopyranoside', 'ethyl beta-glucopyranoside', 'ethylmalonate', 'eugenol sulfate', 'ferulic acid 4-sulfate',
	'ferulylglycine (1)', 'ferulylglycine (2)', 'formiminoglutamate', 'fructosyllysine', 'furaneol sulfate', 'gluconate',
	'glucuronide of C10H14O2 (4)*', 'glucuronide of C10H18O2 (1)*', 'glucuronide of C10H18O2 (11)*', 'glucuronide of C10H18O2 (12)*',
	'glucuronide of C10H18O2 (5)*', 'glucuronide of C10H18O2 (6)*', 'glucuronide of C10H18O2 (7)*', 'glucuronide of C10H18O2 (8)*',
	'glucuronide of C12H20O3 (4)*', 'glucuronide of C12H22O4 (1)*', 'glutamate', 'glutamate, gamma-methyl ester', 'glutamine',
	'glutamine conjugate of C6H10O2 (1)*', 'glutamine conjugate of C6H10O2 (2)*', 'glutamine conjugate of C7H12O2*',
	'glutamine conjugate of C8H12O2 (2)*', 'glutamine_degradant*', 'glutaminylleucine', 'glutarate (C5-DC)', 'glutarylcarnitine (C5-DC)',
	'glycine', 'glycine conjugate of C10H14O2 (1)*', 'glycylisoleucine', 'glycylleucine', 'glycylvaline', 'guaiacol sulfate',
	'heptenedioate (C7:1-DC)*', 'hippurate', 'histamine', 'histidine', 'histidine methyl ester', 'homoarginine', 'homostachydrine*',
	'hydroxy-N6,N6,N6-trimethyllysine*', 'hydroxypalmitoyl sphingomyelin (d18:1/16:0(OH))', 'hypotaurine', 'imidazole lactate',
	'imidazole propionate', 'indoleacetate', 'indoleacetoylcarnitine*', 'indoleacetylglutamine', 'indolelactate', 'indolepropionylglycine',
	'isobutyrylcarnitine (C4)', 'isoleucine', 'isoleucylglycine', 'isovalerylcarnitine (C5)', 'isovalerylglycine', 'kynurenate',
	'kynurenine', 'lanthionine', 'leucine', 'leucylalanine', 'leucylglutamine*', 'leucylglycine', 'lignoceroyl sphingomyelin (d18:1/24:0)',
	'lysine', 'lysylleucine', 'maleate', 'maltol sulfate', 'mannonate*', 'methionine', 'methionine sulfone', 'methionine sulfoxide',
	'methyl-4-hydroxybenzoate', 'methyl-4-hydroxybenzoate sulfate', 'methylsuccinate', 'N(1)-acetylspermine', 'N,N,N-trimethyl-5-aminovalerate',
	'N,N,N-trimethyl-alanylproline betaine (TMAP)', 'N-(2-furoyl)glycine', 'N-acetyl-1-methylhistidine*', 'N-acetyl-3-methylhistidine*',
	'N-acetyl-aspartyl-glutamate (NAAG)', 'N-acetyl-cadaverine', 'N-acetyl-isoputreanine', 'n-Acetyl-s-(2-hydroxypropyl)cysteine',
	'N-acetyl-S-allyl-L-cysteine', 'N-acetylalliin', 'N-acetylarginine', 'N-acetylcitrulline', 'N-acetylcysteine', 'N-acetylglutamate',
	'N-acetylglutamine', 'N-acetylglycine', 'N-acetylhistamine', 'N-acetylhistidine', 'N-acetylhomocitrulline', 'N-acetylisoleucine',
	'N-acetylleucine', 'N-acetylmethionine', 'N-acetylmethionine sulfoxide', 'N-acetylputrescine', 'N-acetylpyrraline', 'N-acetylserine',
	'N-acetyltaurine', 'N-acetylthreonine', 'N-acetyltryptophan', 'N-acetyltyrosine', 'N-acetylvaline', 'N-formylkynurenine',
	'N-formylmethionine', 'N-formylphenylalanine', 'N-methylhydroxyproline', 'N-methylproline', 'N1,N12-diacetylspermine',
	'1-methyladenosine', 'N2,N5-diacetylornithine', 'N2-acetyl,N6-methyllysine', 'N6,N6,N6-trimethyllysine', 'N6,N6-dimethyllysine',
	'N6-carbamoylthreonyladenosine', 'N6-methyllysine', 'naringenin 7-glucuronide', 'o-cresol sulfate', 'O-methyltyrosine',
	'O-sulfo-L-tyrosine', 'o-Tyrosine', 'ornithine', 'p-cresol glucuronide*', 'p-cresol sulfate', 'palmitoyl sphingomyelin (d18:1/16:0)',
	'pentose acid*', 'phenol sulfate', 'phenylalanylalanine', 'phenylalanylglycine', 'picolinate', 'pimelate (C7-DC)', 'pipecolate', 'piperidine',
	'prolylhydroxyproline', 'proline', 'prolylglycine', 'propyl 4-hydroxybenzoate sulfate', 'putrescine', 'pyrraline', 'quinate',
	'S-1-pyrroline-5-carboxylate', 'S-adenosylmethionine (SAM)', 'S-carboxyethylcysteine', 'S-methylcysteine sulfoxide', 'S-methylmethionine',
	'sarcosine', 'sebacate (C10-DC)', 'serine', 'spermidine', 'spermine', 'sphingomyelin (d17:1/16:0, d18:1/15:0, d16:1/17:0)*',
	'sphingomyelin (d18:1/14:0, d16:1/16:0)*', 'sphingomyelin (d18:1/17:0, d17:1/18:0, d19:1/16:0)', 'sphingomyelin (d18:1/20:0, d16:1/22:0)*',
	'sphingomyelin (d18:1/24:1, d18:2/24:0)*', 'sphingomyelin (d18:2/24:1, d18:1/24:2)*', 'stachydrine', 'stearoyl sphingomyelin (d18:1/18:0)',
	'suberate (C8-DC)', 'sulfate of piperine metabolite C16H19NO3 (2)*', 'sulfate of piperine metabolite C16H19NO3 (3)*', 'sulfate*',
	'tartarate', 'tartronate (hydroxymalonate)', 'taurine', 'theanine', 'thioproline', 'threonine', 'threonylphenylalanine',
	'thymol sulfate', 'tiglyl carnitine (C5)', 'hydroxyproline', 'trans-urocanate', 'triethanolamine', 'trizma acetate',
	'tryptamine', 'tryptophan', 'tryptophan betaine', 'tryptophylglycine', 'tyramine', 'tyrosine', 'tyrosylglycine',
	'umbelliferone sulfate', 'undecanedioate (C11-DC)', 'urea', 'valine', 'valylglutamine', 'valylglycine', 'valylleucine',
	'vanillate glucuronide', 'vanillic acid glycine', 'vanillic alcohol sulfate', 'vanillylmandelate (VMA)', 'xanthurenate']

	X = X.loc[order]
	Y = Y.loc[order]

	##### Define folds for 10 fold CV
	##### note - this set of CV folds was randomly chosen during 2000 iterations of hyperparmater
	##### search where each set of hyperparameters was evaluated on a different set of CV folds
	f0 = ['(N(1) + N(8))-acetylspermidine', '1,2,3-benzenetriol sulfate (1)',
		'1-carboxyethylhistidine', '1-carboxyethylisoleucine',
		'1-carboxyethylleucine', '1-carboxyethyltyrosine',
		'1-methyl-4-imidazoleacetate', '1-methyl-5-imidazoleacetate',
		'1-methyladenine', '2,3-dihydroxy-5-methylthio-4-pentenoate (DMTPA)*',
		'2,3-dihydroxyisovalerate', '2-acetamidophenol sulfate',
		'2-aminoadipate', '2-aminophenol sulfate',
		'2-hydroxy-4-(methylthio)butanoic acid', '2-hydroxyadipate',
		'2-hydroxyhippurate (salicylurate)', '2-isopropylmalate',
		'2-methoxyhydroquinone sulfate (1)',
		'2-methoxyhydroquinone sulfate (2)', '2-oxoarginine*',
		'3-(4-hydroxyphenyl)lactate (HPLA)', '3-amino-2-piperidone',
		'3-indoxyl sulfate', '4-acetamidobutanoate', '4-hydroxyglutamate',
		'5-(galactosylhydroxy)-L-lysine', 'alanylleucine', 'allo-threonine',
		'behenoyl sphingomyelin (d18:1/22:0)*', 'glucuronide of C10H14O2 (4)*',
		'glucuronide of C10H18O2 (1)*', 'glutaminylleucine']
	f1 = ['1,2,3-benzenetriol sulfate (2)', '1-carboxyethylvaline',
		'1-methyl-5-imidazolelactate', '1-methylhistamine', "2'-deoxyadenosine",
		'2,3-dihydroxy-2-methylbutyrate', '2-hydroxy-3-methylvalerate',
		'2-hydroxyglutarate', '2-piperidinone', '3-formylindole',
		'3-hydroxyhippurate', '3-hydroxystachydrine*',
		'3-methoxycatechol sulfate (1)', '3-methyl catechol sulfate (1)',
		'3-sulfo-L-alanine', '5-aminovalerate', '5-hydroxylysine',
		'5-methylthioadenosine (MTA)', 'acesulfame', 'agmatine',
		'alpha-ketoglutaramate*', 'argininate*', 'arginine', 'betaine',
		'C-glycosyltryptophan', 'cystathionine', 'dopamine 3-O-sulfate',
		'dopamine 4-sulfate', 'glucuronide of C10H18O2 (11)*',
		'glucuronide of C10H18O2 (12)*', 'glycylisoleucine', 'glycylleucine',
		'hydroxypalmitoyl sphingomyelin (d18:1/16:0(OH))']
	f2 = ['1-methylhistidine', '1-ribosyl-imidazoleacetate*', '2-hydroxysebacate',
		'2-methylbutyrylcarnitine (C5)', '3-hydroxy-2-ethylpropionate',
		'3-hydroxy-2-methylpyridine', '3-hydroxy-2-methylpyridine sulfate',
		'3-hydroxyadipate', '3-hydroxyisobutyrate', '4-acetylphenyl sulfate',
		'4-allylcatechol sulfate', '6-oxopiperidine-2-carboxylate', 'adenine',
		'adenosine', 'argininosuccinate', 'beta-citrylglutamate',
		'beta-guanidinopropanoate', 'betaine aldehyde', 'cinnamoylglycine',
		'citrulline', 'cysteine', 'cystine', 'diacetylspermidine*',
		'dihydrocaffeate sulfate (2)', 'erythritol',
		'glucuronide of C10H18O2 (5)*', 'glucuronide of C10H18O2 (6)*',
		'glycylvaline', 'indoleacetate', 'indoleacetoylcarnitine*',
		'isoleucylglycine', 'lignoceroyl sphingomyelin (d18:1/24:0)',
		'N-acetyltyrosine']
	f3 = ['3-hydroxydodecanedioate*', '3-hydroxypyridine sulfate',
		'3-methyl-2-oxobutyrate', '3-methyladipate', '3-methylglutaconate',
		'3-methylglutarylcarnitine (2)', '3-methylhistidine',
		'4-ethylcatechol sulfate', '4-ethylphenyl sulfate',
		'4-imidazoleacetate', '5-hydroxy-2-methylpyridine sulfate', "2'-AMP",
		'cadaverine', 'carboxyethyl-GABA', 'dimethylarginine (ADMA + SDMA)',
		'dimethylglycine', 'ethyl alpha-glucopyranoside',
		'ethyl beta-glucopyranoside', 'eugenol sulfate',
		'ferulic acid 4-sulfate', 'glucuronide of C10H18O2 (7)*',
		'glucuronide of C10H18O2 (8)*', 'homoarginine', 'hypotaurine',
		'indoleacetylglutamine', 'indolelactate', 'lanthionine',
		'leucylalanine', 'leucylglutamine*', 'methionine',
		'N(1)-acetylspermine', 'N-formylphenylalanine',
		'palmitoyl sphingomyelin (d18:1/16:0)']
	f4 = ['3-methylglutarate/2-methylglutarate', '4-hydroxyhippurate',
		'4-methylcatechol sulfate', '6-hydroxyindole sulfate',
		"adenosine 3',5'-cyclic monophosphate (cAMP)", 'adipate',
		'alpha-hydroxyisocaproate', 'alpha-hydroxyisovalerate', 'anserine',
		'beta-hydroxyisovalerate', 'cis-urocanate', 'dexpanthenol',
		'ferulylglycine (1)', 'ferulylglycine (2)', 'fructosyllysine',
		'furaneol sulfate', 'gluconate', 'glucuronide of C12H20O3 (4)*',
		'glucuronide of C12H22O4 (1)*', 'glutamate', 'glycine',
		'homostachydrine*', 'indolepropionylglycine', 'kynurenate',
		'leucylglycine', 'lysylleucine', 'methionine sulfone',
		'methionine sulfoxide', 'N,N,N-trimethyl-alanylproline betaine (TMAP)',
		'N-acetyl-isoputreanine', 'N-acetylarginine', 'O-methyltyrosine',
		'sphingomyelin (d17:1/16:0, d18:1/15:0, d16:1/17:0)*']
	f5 = ['4-methylguaiacol sulfate', '4-vinylcatechol sulfate', "3'-AMP",
		'azelate (C9-DC)', 'beta-hydroxyisovaleroylcarnitine', 'diethanolamine',
		'diglycerol', 'dimethylmalonic acid', 'ethylmalonate',
		'formiminoglutamate', 'glutamate, gamma-methyl ester',
		'glutamine conjugate of C6H10O2 (1)*',
		'glutamine conjugate of C6H10O2 (2)*', 'glutarylcarnitine (C5-DC)',
		'histamine', 'hydroxy-N6,N6,N6-trimethyllysine*',
		'isobutyrylcarnitine (C4)', 'kynurenine', 'maltol sulfate',
		'mannonate*', 'N-(2-furoyl)glycine', 'N-acetyl-S-allyl-L-cysteine',
		'N-acetylcitrulline', 'N-acetylcysteine', 'N-acetylglycine',
		'N-acetylhomocitrulline', 'N-acetylmethionine', 'N-acetylputrescine',
		'N-acetyltryptophan', 'o-Tyrosine', 'phenylalanylalanine',
		'phenylalanylglycine', 'sphingomyelin (d18:1/14:0, d16:1/16:0)*']
	f6 = ['4-vinylphenol sulfate', 'AMP', 'catechol sulfate', 'EDTA', 'glutamine',
		'glutamine conjugate of C7H12O2*',
		'glutamine conjugate of C8H12O2 (2)*', 'glutarate (C5-DC)',
		'heptenedioate (C7:1-DC)*', 'histidine', 'histidine methyl ester',
		'isoleucine', 'isovalerylcarnitine (C5)', 'isovalerylglycine', 'lysine',
		'N,N,N-trimethyl-5-aminovalerate',
		'n-Acetyl-s-(2-hydroxypropyl)cysteine', 'N-acetylalliin',
		'N-acetylmethionine sulfoxide', 'N-acetylpyrraline', 'N-acetylserine',
		'N-acetyltaurine', 'N-formylkynurenine', 'N-methylhydroxyproline',
		'N-methylproline', 'N1,N12-diacetylspermine',
		'naringenin 7-glucuronide', 'p-cresol glucuronide*', 'picolinate',
		'piperidine', 'prolylglycine',
		'sphingomyelin (d18:1/17:0, d17:1/18:0, d19:1/16:0)',
		'threonylphenylalanine']
	f7 = ['cyclic adenosine diphosphate-ribose', 'glutamine_degradant*',
		'guaiacol sulfate', 'hippurate', 'imidazole lactate',
		'imidazole propionate', 'leucine', 'maleate', 'methylsuccinate',
		'N-acetyl-aspartyl-glutamate (NAAG)', 'N-acetyl-cadaverine',
		'N-acetylisoleucine', 'N-acetylthreonine', 'N-formylmethionine',
		'N2,N5-diacetylornithine', 'N2-acetyl,N6-methyllysine',
		'O-sulfo-L-tyrosine', 'ornithine', 'phenol sulfate', 'pimelate (C7-DC)',
		'putrescine', 'pyrraline', 'quinate', 'S-adenosylmethionine (SAM)',
		'sphingomyelin (d18:1/20:0, d16:1/22:0)*', 'stachydrine',
		'sulfate of piperine metabolite C16H19NO3 (2)*', 'sulfate*',
		'tryptamine', 'tryptophan', 'tryptophylglycine', 'tyrosylglycine']
	f8 = ['glycine conjugate of C10H14O2 (1)*', 'methyl-4-hydroxybenzoate',
		'methyl-4-hydroxybenzoate sulfate', 'N-acetyl-1-methylhistidine*',
		'N-acetyl-3-methylhistidine*', 'N-acetylglutamate', 'N-acetylglutamine',
		'N-acetylleucine', 'N-acetylvaline', '1-methyladenosine',
		'N6,N6,N6-trimethyllysine', 'N6,N6-dimethyllysine',
		'prolylhydroxyproline', 'proline', 'S-carboxyethylcysteine',
		'S-methylcysteine sulfoxide', 'sarcosine', 'sebacate (C10-DC)',
		'serine', 'spermidine', 'sphingomyelin (d18:1/24:1, d18:2/24:0)*',
		'suberate (C8-DC)', 'sulfate of piperine metabolite C16H19NO3 (3)*',
		'tartarate', 'tartronate (hydroxymalonate)', 'theanine', 'thioproline',
		'triethanolamine', 'tryptophan betaine', 'tyramine', 'tyrosine',
		'valylglutamine']
	f9 = ['N-acetylhistamine', 'N-acetylhistidine',
		'N6-carbamoylthreonyladenosine', 'N6-methyllysine', 'o-cresol sulfate',
		'p-cresol sulfate', 'pentose acid*', 'pipecolate',
		'propyl 4-hydroxybenzoate sulfate', 'S-1-pyrroline-5-carboxylate',
		'S-methylmethionine', 'spermine',
		'sphingomyelin (d18:2/24:1, d18:1/24:2)*',
		'stearoyl sphingomyelin (d18:1/18:0)', 'taurine', 'threonine',
		'thymol sulfate', 'tiglyl carnitine (C5)', 'hydroxyproline',
		'trans-urocanate', 'trizma acetate', 'umbelliferone sulfate',
		'undecanedioate (C11-DC)', 'urea', 'valine', 'valylglycine',
		'valylleucine', 'vanillate glucuronide', 'vanillic acid glycine',
		'vanillic alcohol sulfate', 'vanillylmandelate (VMA)', 'xanthurenate']


	folds = [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
	preds = []

	for f in folds:

		x_test = X.loc[f]
		y_train = Y.drop(f)
		x_train = X.drop(f)

		params = {
			'objective': 'multiclass',
			'num_leaves': 65,
			'max_depth': 9,
			'learning_rate': 0.1,
			'subsample': 0.75,  
			'colsample_bytree': 0.8,
			'class_weight': 'balanced',
			'num_iterations': 4000,
			'min_child_samples': 23,
			'categorical_feature': 234,
			'reg_lambda':0,
			'n_jobs': 1,
			'subsample_freq': 1,
			'random_state': 420,
			'bagging_seed': 420,
			'feature_fraction_seed': 420,
			'data_random_seed': 420,
			'extra_seed': 420,
			}


		model = lgb.LGBMClassifier(**params)

		model.fit(x_train, np.ravel(y_train.values))
		y_pred = model.predict_proba(x_test)
		y_pred = pd.DataFrame(y_pred, index=f)
		preds.append(y_pred)

	predictions = pd.concat(preds)
	predictions.columns = Y['Sub pathway'].sort_values().unique() 


	##### Figure S8A - confusion matrix of true and predicted sub pathway labels
	## Order by corresponding super pathways
	order = ['Benzoate Metabolism',
            'Chemical',
            'Food Component/Plant',
            'Glutamate Metabolism',
            'Glycine, Serine and Threonine Metabolism',
            'Histidine Metabolism',
            'Leucine, Isoleucine and Valine Metabolism',
            'Lysine Metabolism',
            'Methionine, Cysteine, SAM and Taurine Metabolism',
            'Polyamine Metabolism',
            'Tryptophan Metabolism',
            'Tyrosine Metabolism',
            'Urea cycle; Arginine and Proline Metabolism',
            'Fatty Acid, Dicarboxylate',
            'Sphingomyelins',
            'Dipeptide',
            'Purine Metabolism, Adenine containing',
            'Partially Characterized Molecules']

    ## Identify top predicted label 
	pred_ys = []
	for m in predictions.index:
	    pred_ys.append(predictions.loc[m, :].sort_values(ascending=False).index[0])
	predictions['predicted_label'] = pred_ys

	## join with true label
	predictions = predictions.loc[Y.index]
	predictions = predictions.join(Y['Sub pathway'])

	cm = pd.crosstab(predictions['Sub pathway'], predictions['predicted_label'])
	cm['Support'] = cm.sum(axis=1)
	cm = cm.loc[order]
	cm = cm[order + ['Support']]

	plt.figure(figsize=(12,10))
	sns.heatmap(cm, annot=True, cmap='coolwarm', center=0, cbar=False)
	plt.xlabel("")
	plt.ylabel("")
	plt.savefig("figurePanels/S8A.pdf", dpi=800, bbox_inches='tight')


	#### Figure S8B - Accuracies of top K predictions
	preds_only = predictions.copy().drop(['predicted_label', 'Sub pathway'], axis=1)
	accuracies = []
	for k in range(1, 7):
		N_correct = 0
		for m in predictions.index:
			y_true = predictions.loc[m]['Sub pathway']
			top_k = list(preds_only.loc[m].sort_values(ascending=False).index[0:k])
			if y_true in top_k:
				N_correct = N_correct + 1
		acc = N_correct / predictions.shape[0]
		accuracies.append(acc)
	print(accuracies)
	plt.figure(figsize=(6,4))
	plt.bar(np.arange(1, len(accuracies)+1), accuracies)
	plt.savefig("figurePanels/S8B.pdf", dpi=800, bbox_inches='tight')


	#### Figure S8D - Accuracy and fraction of metabolites with top prediction above a theshold
	#### at different thresholds on the top predictions 
	thresholds = np.arange(0,1,.005)
	y_true = predictions['Sub pathway']

	m_frac_arr = []
	acc_arr = []

	for t in thresholds:
	    m_frac_above = np.sum(preds_only.max(axis=1) > t) / preds_only.shape[0]
	    
	    to_consider = preds_only.loc[preds_only.max(axis=1) > t]
	    n_correct = 0
	    for m in to_consider.index:
	        top_pred = to_consider.loc[m,:].sort_values(ascending=False).index[0]
	        if top_pred == y_true.loc[m]:
	            n_correct = n_correct + 1
	    acc = n_correct / to_consider.shape[0]
	    
	    m_frac_arr.append(m_frac_above)
	    acc_arr.append(acc)


	fig, ax1 = plt.subplots(figsize=(6,4))
	ax1.scatter(thresholds, acc_arr, color='tab:red', facecolors='none')
	ax2 = ax1.twinx() 
	ax2.scatter(thresholds, m_frac_arr, color='tab:blue', facecolors='none')
	ymin, ymax = ax2.get_ylim()
	ax1.set_ylim(ymin, ymax)
	plt.savefig("figurePanels/S8D.pdf", dpi=800, bbox_inches='tight')


## Figure S8C - sub pathway predictions for unknown metabolites 
## associated with sPTB or TB
def figure_S8C():

	X_train, Y_train = get_sp_pred_data()

	## construct X_test
	test_metabs = ['X - 25656', 'X - 25828', 'X - 11381', 'X - 25861', 'X - 14056']
	X_test = get_metabs(min_impute=True, rzscore=True).T
	X_test = X_test.loc[test_metabs]
	m_raw = get_metabs(min_impute=False, rzscore=False).T
	X_test['sparsity'] = m_raw.isnull().sum(axis=1)
	m_raw = m_raw.loc[test_metabs]
	X_test['raw_mean'] = m_raw.mean(axis=1)
	m_platforms = get_metab_platforms()
	m_platforms['PLATFORM'] = m_platforms['PLATFORM'].map({'LC/MS Pos Early':0,
															'LC/MS Pos Late':1,
															'LC/MS Polar':2,
															'LC/MS Neg':3})
	X_test = X_test.join(m_platforms)
	mass_and_ri = get_unknowns_mass_RI()
	X_test = X_test.join(mass_and_ri)

	## perform feature filtering
	def perform_feature_filtering(X_train, X_test, ff_threshold):
	    modes = list(X_train.mode().iloc[0,:])
	    filtered_features = list((X_train != modes).sum().sort_values(ascending=False)[:int(np.ceil(ff_threshold * len(X_train.columns)))].index)
	    X_train_filtered = X_train.loc[:, filtered_features]
	    X_test_filtered = X_test.loc[:, filtered_features]

	    return X_train_filtered, X_test_filtered

	X_train_filtered, X_test_filtered = perform_feature_filtering(X_train, X_test, 0.6)

	## params from best model
	params = {
				'objective': 'multiclass',
				'num_leaves': 65,
				'max_depth': 9,
				'learning_rate': 0.1,
				'subsample': 0.75,  
				'colsample_bytree': 0.8,
				'reg_lambda':0,
				'class_weight': 'balanced',
				'num_iterations': 4000,
				'min_child_samples': 23,
				'categorical_feature': 234
			}

	model = lgb.LGBMClassifier(**params)
	model.fit(X_train_filtered, np.ravel(Y_train.values))

	y_pred = model.predict_proba(X_test_filtered)

	unknown_predictions = pd.DataFrame(y_pred)
	unknown_predictions.columns = Y_train['Sub pathway'].sort_values().unique()
	unknown_predictions.index = X_test.index
	
	for x in unknown_predictions.index:
	    top_pred = unknown_predictions.loc[x, :].sort_values(ascending=False).index[0]
	    top_pred_proba = unknown_predictions.loc[x, :].sort_values(ascending=False)[0]
	    
	    second_pred = unknown_predictions.loc[x, :].sort_values(ascending=False).index[1]
	    second_pred_proba = unknown_predictions.loc[x, :].sort_values(ascending=False)[1]
	    print(x)
	    print(top_pred)
	    print(top_pred_proba)
	    print(second_pred)
	    print(second_pred_proba)
